---
# Codacy static analysis (https://app.codacy.com/gh/dimmmmmmmer/freetunnel).
exclude_paths:
  - 'ci-artifacts-latest/**'
  - 'tests/**'
  - '**/_deps/**'
  - '**/build*/**'
  - 'docs/**'

engines:
  cppcheck:
    language: c++
    extra_lines:
      - "--suppress=missingInclude"
      - "--suppress=missingIncludeSystem"
      - "--suppress=unknownMacro"
      - "--suppress=passedByValue"
      - "--suppress=sizeofwithnumericparameter"
      - "--suppress=unusedStructMember"
      - "--inline-suppr"
      - "--library=qt"
      - "-I include"
      - "-I include/app"
      - "-I include/core"
      - "-I include/vpn"
      - "--std=c++20"
      - "--enable=warning,performance,portability"
  lizard:
    exclude_paths:
      - 'i18n/**'
  metric:
    exclude_paths:
      - 'i18n/**'
  duplication:
    exclude_paths:
      - 'i18n/**'
