######################################################################
# Automatically generated by qmake (3.1) Sun Jun 14 18:33:57 2026
######################################################################

TEMPLATE = app
TARGET = tests
INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_UP_TO=0x060000 # disables all APIs deprecated in Qt 6.0.0 and earlier

# Input
SOURCES += test_appsettings.cpp \
           test_configimport.cpp \
           test_configstore.cpp \
           test_control.cpp \
           test_deeplink.cpp \
           build/test_appsettings_autogen/mocs_compilation.cpp \
           build/test_configimport_autogen/mocs_compilation.cpp \
           build/test_configstore_autogen/mocs_compilation.cpp \
           build/test_control_autogen/mocs_compilation.cpp \
           build/test_deeplink_autogen/mocs_compilation.cpp \
           build/CMakeFiles/4.3.3/CompilerIdCXX/apple-sdk.cpp \
           build/CMakeFiles/4.3.3/CompilerIdCXX/CMakeCXXCompilerId.cpp
TRANSLATIONS += build/CMakeFiles/test_appsettings.dir/compiler_depend.ts \
                build/CMakeFiles/test_appsettings_autogen.dir/compiler_depend.ts \
                build/CMakeFiles/test_appsettings_autogen_timestamp_deps.dir/compiler_depend.ts \
                build/CMakeFiles/test_configimport.dir/compiler_depend.ts \
                build/CMakeFiles/test_configimport_autogen.dir/compiler_depend.ts \
                build/CMakeFiles/test_configimport_autogen_timestamp_deps.dir/compiler_depend.ts \
                build/CMakeFiles/test_configstore.dir/compiler_depend.ts \
                build/CMakeFiles/test_configstore_autogen.dir/compiler_depend.ts \
                build/CMakeFiles/test_configstore_autogen_timestamp_deps.dir/compiler_depend.ts \
                build/CMakeFiles/test_control.dir/compiler_depend.ts \
                build/CMakeFiles/test_control_autogen.dir/compiler_depend.ts \
                build/CMakeFiles/test_control_autogen_timestamp_deps.dir/compiler_depend.ts \
                build/CMakeFiles/test_deeplink.dir/compiler_depend.ts \
                build/CMakeFiles/test_deeplink_autogen.dir/compiler_depend.ts \
                build/CMakeFiles/test_deeplink_autogen_timestamp_deps.dir/compiler_depend.ts
